### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by piegit** [shinyquagsire23/arcshark#3]
zlib.h missing file or directory

**Comment by aliig** [comment]
If you're in Ubuntu, try this `sudo apt install zlib1g`

**Comment by piegit** [comment]
I'm on windows

**Comment by aliig** [comment]
@piegit  You can google `zlib1g for windows` and try one of the solutions there. You can also install install Ubuntu on Windows 10 through the Microsoft Store.

**Comment by piegit** [comment]
@mgleed im on WSL Ubuntu 18.04 Ubuntu LTS and it still says zlib.h not found

**Comment by piegit** [comment]
oh nvm @mgleed I fixed it by installing zlib1g-dev but now im getting that crc32 error

**Comment by piegit** [comment]
oh actually im getting this `main.cpp: In function ‘int main(int, char**)’:
main.cpp:135:44: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
     printf("Magic: %016llx\n", header.magic);`

**Comment by piegit** [comment]
oh I got it working now, I did `g++ main.cpp -lz && ./a.out data.arc` and it worked
